---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apparmor-profiles
data:
  deny-write.profile: |
    #include <tunables/global>
    profile k8s-apparmor-example-deny-write flags=(attach_disconnected) {
      #include <abstractions/base>

      file,
      # Deny all file writes.
      deny /** w,
    }